# Generated by Django 5.1.1 on 2024-09-11 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_i_sh', models.CharField(max_length=100, verbose_name='F.I.SH')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('homiylik_summa', models.IntegerField(verbose_name='Homiylik summasi')),
                ('sarflangan_summa', models.IntegerField(verbose_name='Sarflangan summa')),
                ('sana', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('status', models.CharField(choices=[('yangi', 'Yangi'), ('moderatsiyada', 'Moderatsiyada'), ('tasdiqlangan', 'Tasdiqlangan'), ('bekor_qilingan', 'Bekor qilingan')], max_length=20, verbose_name='Holati')),
                ('amallar', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Homiy',
                'verbose_name_plural': 'Homiylar',
            },
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_i_sh', models.CharField(max_length=100, verbose_name='F.I.SH')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('otm', models.CharField(choices=[('O’zbekiston milliy universiteti', 'O’zbekiston milliy universiteti'), ('Toshkent davlat texnika universiteti', 'Toshkent davlat texnika universiteti'), ('Toshkent davlat iqtisodiyot universiteti', 'Toshkent davlat iqtisodiyot universiteti'), ('O’zbekiston davlat jahon tillari universiteti', 'O’zbekiston davlat jahon tillari universiteti'), ('Toshkent davlat sharqshunoslik instituti', 'Toshkent davlat sharqshunoslik instituti'), ('Toshkent arxitektura-qurilish instituti', 'Toshkent arxitektura-qurilish instituti'), ('Toshkent avtomobil-yo’llari instituti', 'Toshkent avtomobil-yo’llari instituti'), ('Toshkent moliya instituti', 'Toshkent moliya instituti'), ('Toshkent davlat pedagogika universiteti', 'Toshkent davlat pedagogika universiteti'), ('Samarqand davlat universiteti', 'Samarqand davlat universiteti')], max_length=100, verbose_name='OTM')),
                ('talabalik_turi', models.CharField(choices=[('bakalavr', 'Bakalavr'), ('magistr', 'Magistr')], max_length=20, verbose_name='Talabalik turi')),
                ('kontrakt_summa', models.IntegerField(verbose_name='Kontrakt summa')),
                ('atratilgan_summa', models.IntegerField(verbose_name='Ajratilgan summa')),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
            },
        ),
        migrations.CreateModel(
            name='TalabaVaHomiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajratilgan_summa', models.IntegerField(null=True)),
                ('homiy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metsenat.homiy')),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metsenat.talaba')),
            ],
        ),
        migrations.AddField(
            model_name='talaba',
            name='homiylar',
            field=models.ManyToManyField(related_name='talabalar', through='metsenat.TalabaVaHomiy', to='metsenat.homiy', verbose_name='Homiylar'),
        ),
    ]
